### ISSUE TITLE
Cannot view to choose hidden '.gradle' folder on MacOS

### ISSUE THREAD

**Issue by ashwin-yo** [jonatan-kazmierczak/class-visualizer#11]
When I click click on "File -> Add Required Libraries -> directories/JAR files...", I cannot see the "~/.gradle" folder (or any hidden folders) in MacOS Ventura 13.2 to select.

**Comment by jonatan-kazmierczak** [comment]
Hi @ashwin-yo , Thanks for the info.    
It seems to be a limitation of the Open/Save dialog (I have to double check it).  
Workaround: see http://class-visualizer.net/faq.html , section *How can I load a Gradle-based application?*

**Comment by jonatan-kazmierczak** [comment]
Hi @ashwin-yo ,
hidden dirs are visible in v17.0.0
