### ISSUE TITLE
tried to open a folder and I get "no classes loaded"

### ISSUE THREAD

**Issue by ppazos** [jonatan-kazmierczak/class-visualizer#2]
the project I try to open is a clone from https://github.com/dcm4che/dcm4chee-xds

maybe I'm doing something wrong, how can I load all the classes from that project?

thanks!

**Comment by jonatan-kazmierczak** [comment]
Please look at http://class-visualizer.net/faq.html - standard question nr 2 :)

**Comment by ppazos** [comment]
thanks @jonatan-kazmierczak that project is maven based, so I think question 3 applies, but going to the link for the loading process description, I can see only some screenshots of already loaded project. Is there a step by step guide on loading a maven based project?

**Comment by jonatan-kazmierczak** [comment]
Thanks for pointing that out - the content was out-of-sync.  
Now links in FAQ should point to right videos :)

**Comment by jonatan-kazmierczak** [comment]
Hi @ppazos , is everything OK? If yes, would you like to close the issue?

**Comment by ppazos** [comment]
hey @jonatan-kazmierczak yes I can close it, I couldn't test it yet because the project that I want to run this over is not building due problems with dependencies, I already reported those error to the developers, so I would try again when those are solved. Thanks!
