### ISSUE TITLE
java class files not visible

### ISSUE THREAD

**Issue by jeltedeproft** [jonatan-kazmierczak/class-visualizer#6]
When I am trying to add my classes through the class file directory picker. My class files are not visible.
If I use the jar finder, then they are visible.

**Comment by jonatan-kazmierczak** [comment]
Hi @jeltedeproft ,
Sorry for my delayed answer.  
The option `Load classes -> from directory...` opens dialog with a title "Choose **class root directory** to load classes from".  
In case of doubt, how to use it, please take a look at [this demo](https://www.youtube.com/watch?v=qGLPHAnW_58&feature=youtu.be&t=487) (referenced from [project FAQ page](http://class-visualizer.net/faq.html)).  
Please let me know if you are able to load classes now.

**Comment by jeltedeproft** [comment]
hi @jonatan-kazmierczak , I have followed the demo and tried adding classes from directory, but none of them are showing up.
I open the bin folder in eclipse, where all the class files are located, but it doesn't show them. Might this be a java version issue?

**Comment by jonatan-kazmierczak** [comment]
Hi @jeltedeproft ,
As I wrote above:
> The option `Load classes -> from directory...` opens dialog with a title "Choose **class root directory** to load classes from".  

Mentioned video demonstrates this option.  

Please note, that only directories are shown in the *Open* dialog, not classes. Please check with some file explorer or `find` command, if you have any compiled classes under your *classes root directory* (I understand, that it's *bin* in your case). If not, you have to build your project.  
Please check in the Log of Class Visualizer (at the bottom) if you have any errors; if any, please read them first and then please copy them here so I will be able to fully understand your issue.

**Comment by jonatan-kazmierczak** [comment]
Required info not provided for 25 days -> no real issue or not important -> closing
