### ISSUE TITLE
I cannot visualize java9 module in class-visualizer? Do you know how to do in class-visulaizer?

### ISSUE THREAD

**Issue by MehmoodHashmi** [jonatan-kazmierczak/class-visualizer#7]

**Comment by jonatan-kazmierczak** [comment]
Hi @MehmoodHashmi , sorry for my delayed answer.
Please see updated site https://class-visualizer.net/faq.html (point 3) and let me know if you are able to load the module.

**Comment by jonatan-kazmierczak** [comment]
No more comments about the issue for 8 days = solved.

**Comment by MehmoodHashmi** [comment]
thank you Jonatan-kazmierczak.
