### ISSUE TITLE
Hi, I met with a problem when using the programme.

### ISSUE THREAD

**Issue by passingby000** [jonatan-kazmierczak/class-visualizer#9]
java.lang.UnsupportedClassVersionError: Exceptions/IllegalOperatingException has been compiled by a more recent version of the Java Runtime (class file version 62.0), this version of the Java Runtime only recognizes class file versions up to 60.0

I cannot load my class into it.

Thank you for your great work! I love that tool.

**Comment by jonatan-kazmierczak** [comment]
You've started Class Visualizer with older JDK than the compiled classes which you're trying to load. Setting JAVA_HOME pointing to the new enough JDK will help.  
`Help` -> `About` shows an info about the JDK on which Class Visualizer runs - it may also be useful.

**Comment by passingby000** [comment]
Thank you!
